spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=${ENDPOINT_PATH}/products/**
         
            

server:
  port: 8090
