
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: product-service
            uri: lb://PRODUCT-SERVICE
            predicates: 
              -Path=${endpoint.path}/products/**,${endpoint.path}/categories/**

          - id: order-service
            uri: lb://ORDER-SERVICE
            predicates: 
              -Path=/codycod/corporation/v1/orders/**,${endpoint.path}/message/**

          - id: customer-service
            uri:  lb://CUSTOMER-SERVICE
            predicates: 
              -Path=${endpoint.path}/customers/**
            
server:
  port: 8090


