spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            Path:
              - ${ENDPOINT_PATH}/products/**
              - ${ENDPOINT_PATH}/categories/**
            

server:
  port: 8090
