spring:
  application:
    name: api-gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      routes:
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates: 
            -Path=${endpoint.path}/products/**
            -Path=${endpoint.path}/categories/**

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates: 
            -Path=/codycod/corporation/v1/orders/**
            -Path=${endpoint.path}/message/**

        - id: customer-service
          uri:  lb://CUSTOMER-SERVICE
          predicates: 
            -Path=${endpoint.path}/customers/**
            
server:
  port: 8090
