spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=${ENDPOINT_PATH}/products/**,${ENDPOINT_PATH}/categories/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=${ENDPOINT_PATH}/orders/**,${ENDPOINT_PATH}/message/**
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=${ENDPOINT_PATH}/customers/**
            

server:
  port: 8090
