spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: ln://PRODUCT-SERVICE
          predicates:
            - Path=/codycod/corporation/v1/products/**
            - Path=/codycod/corporation/v1/categories/**

server:
  port: 8090
