spring:
  application:
    name: Product-Service
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQLDialect5
    hibernate:
      ddl-auto: create-drop

endpoint:
  path: /codycod/corporation/v1

database:
  name: db_products_service

server:
  port: 8085

