spring:
  application:
    name: BurgerStore [Product Service]
  #setting for this service
  configj:
    impohrt: configserver:http://localhost:1717
      

endpoint:
  path: ${codycod.uri}/products

database:
  name: db_products_service

server:
  port: 8085
