spring:
  application:
    name: Product-Service
  datasource:
    #change credentials and create a database in MySQL with the name db_products_service

    url: jdbc:mysql://localhost:3306/db_products_service
    username: ${DB_MYSQL_USERNAME}
    password: ${DB_MYSQL_PASSWORD}
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQLDialect5
    hibernate:
      ddl-auto: create-drop

endpoint:
  path: /codycod/corporation/v1

server:
  port: 8085
