spring:
  application:
    name: BurgerStore [Product-Service]
  #setting for this service
  config:
    import:
      - ${cofigserver.import.uri}/database-configuration
      - ${cofigserver.import.uri}/jpa-configuration
      - ${cofigserver.import.uri}/eureka-client-configuration

endpoint:
  path: ${codycod.uri}/products

database:
  name: db_products_service

server:
  port: 8085

